[package]
name = "wasp-hls"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/rs-core/lib.rs"

[dependencies]
wasm-bindgen = "0.2.80"
thiserror = "1.0.37"
mse_fmp4 = "0.2.0"
mpeg2ts = "0.2.0"
