// This file is generated by scripts/generate_wasm_abi_bindings.mjs.
// Do not edit it manually.
import type {
  AddSourceBufferErrorCode,
  AttachMediaSourceErrorCode,
  ContentCompatibilityErrorCode,
  EndOfStreamErrorCode,
  LogLevel,
  MediaPlaylistParsingErrorCode,
  MediaSourceDurationUpdateErrorCode,
  MediaSourceReadyState,
  MediaType,
  MultivariantPlaylistParsingErrorCode,
  OtherErrorCode,
  PlaybackTickReason,
  PlaylistNature,
  PlaylistType,
  PushedSegmentErrorCode,
  RemoveBufferErrorCode,
  RemoveMediaSourceErrorCode,
  RequestErrorReason,
  SegmentParsingErrorCode,
  SourceBufferCreationErrorCode,
  StartingPositionType,
  TimerReason,
} from "./enums.js";
import type {
  AppendBufferValue,
  HostResult,
  InspectSegmentValue,
  SegmentHints,
} from "./types.js";
export interface HostBindings {
  /**
   * Abort a pending network request identified by its request id.
   */
  abortRequest(requestId: number): boolean;
  /**
   * Create a SourceBuffer for the given media type and MIME type.
   */
  addSourceBuffer(
    mediaType: MediaType,
    typ: string,
  ): HostResult<number, AddSourceBufferErrorCode>;
  /**
   * Report freshly parsed content metadata back to the host.
   */
  announceFetchedContent(
    playlistType: PlaylistType,
    variantInfo: Uint32Array,
    audioTracksInfo: Uint32Array,
  ): void;
  /**
   * Report an audio or video track selection update to the host.
   */
  announceTrackUpdate(
    mediaType: MediaType,
    trackId: number | undefined,
    isSelected: boolean,
  ): void;
  /**
   * Report that variant lock state changed.
   */
  announceVariantLockStatusChange(variantId: number | undefined): void;
  /**
   * Report the currently selected variant update.
   */
  announceVariantUpdate(variantId: number | undefined): void;
  /**
   * Append one media segment to a SourceBuffer.
   *
   * Notes:
   * - The JS marshalling for this binding is intentionally still handwritten because the return payload is packed.
   */
  appendBuffer(
    sourceBufferId: number,
    resourceId: number,
    segmentHints: SegmentHints,
  ): HostResult<AppendBufferValue, SegmentParsingErrorCode>;
  /**
   * Create and attach a MediaSource to the host media element.
   */
  attachMediaSource(): HostResult<true, AttachMediaSourceErrorCode>;
  /**
   * Cancel a timer previously started by wasm.
   */
  clearTimer(id: number): void;
  /**
   * Copy resource bytes into wasm memory.
   *
   * Notes:
   * - This shares the same host method as `__js_func__get_resource_len`; only the low-level ABI differs.
   */
  getResourceData(id: number): Uint8Array | undefined;
  /**
   * Signal end-of-stream to the active MediaSource.
   */
  endOfStream(): HostResult<true, EndOfStreamErrorCode>;
  /**
   * Start a network request from JavaScript.
   */
  fetch(
    url: string,
    rangeBase: number | undefined,
    rangeEnd: number | undefined,
    timeout: number,
  ): number;
  /**
   * Flush pending host-side buffered state.
   */
  flush(): void;
  /**
   * Release a JavaScript-side resource buffer.
   */
  freeResource(resourceId: number): boolean;
  /**
   * Return a random floating-point value.
   */
  getRandom(): number;
  /**
   * Inspect a segment resource to extract codec and MIME metadata.
   *
   * Notes:
   * - The JS marshalling for this binding is intentionally still handwritten because the success payload is multi-field.
   */
  inspectSegment(
    resourceId: number,
  ): HostResult<InspectSegmentValue, SegmentParsingErrorCode>;
  /**
   * Ask the host whether a MIME type is supported.
   */
  isTypeSupported(mediaType: MediaType, typ: string): boolean | undefined;
  /**
   * Send a log line to the host environment.
   */
  log(logLevel: LogLevel, log: string): void;
  /**
   * Remove buffered media data from a SourceBuffer.
   */
  removeBuffer(
    sourceBufferId: number,
    start: number,
    end: number,
  ): HostResult<true, RemoveBufferErrorCode>;
  /**
   * Detach and clean up the current MediaSource.
   */
  removeMediaSource(): HostResult<true, RemoveMediaSourceErrorCode>;
  /**
   * Seek the media element to a new playback position.
   */
  seek(position: number): void;
  /**
   * Emit a media-playlist parsing error to the host.
   */
  sendMediaPlaylistParsingError(
    fatal: boolean,
    code: MediaPlaylistParsingErrorCode,
    mediaType: MediaType | undefined,
    message: string,
  ): void;
  /**
   * Emit a media-playlist request error to the host.
   */
  sendMediaPlaylistRequestError(
    fatal: boolean,
    url: string,
    reason: RequestErrorReason,
    mediaType: MediaType | undefined,
    status: number | undefined,
  ): void;
  /**
   * Emit a multivariant-playlist parsing error to the host.
   */
  sendMultivariantPlaylistParsingError(
    fatal: boolean,
    code: MultivariantPlaylistParsingErrorCode,
    message: string,
  ): void;
  /**
   * Emit a multivariant-playlist request error to the host.
   */
  sendMultivariantPlaylistRequestError(
    fatal: boolean,
    url: string,
    reason: RequestErrorReason,
    status: number | undefined,
  ): void;
  /**
   * Emit a generic error to the host.
   */
  sendOtherError(fatal: boolean, code: OtherErrorCode, message: string): void;
  /**
   * Emit a content-compatibility error to the host.
   */
  sendContentCompatibilityError(
    fatal: boolean,
    code: ContentCompatibilityErrorCode,
    message: string,
  ): void;
  /**
   * Emit a pushed-segment processing error to the host.
   */
  sendPushedSegmentError(
    fatal: boolean,
    code: PushedSegmentErrorCode,
    mediaType: MediaType,
    message: string,
  ): void;
  /**
   * Emit a remove-buffer error to the host.
   */
  sendRemoveBufferError(
    fatal: boolean,
    mediaType: MediaType,
    message: string,
  ): void;
  /**
   * Emit a segment parsing error to the host.
   */
  sendSegmentParsingError(
    fatal: boolean,
    code: SegmentParsingErrorCode,
    mediaType: MediaType | undefined,
    message: string,
  ): void;
  /**
   * Emit a segment request error to the host.
   */
  sendSegmentRequestError(
    fatal: boolean,
    url: string,
    isInit: boolean,
    timeInfo: [number, number] | undefined,
    mediaType: MediaType | undefined,
    reason: RequestErrorReason,
    status: number | undefined,
  ): void;
  /**
   * Emit a SourceBuffer creation error to the host.
   */
  sendSourceBufferCreationError(
    fatal: boolean,
    code: SourceBufferCreationErrorCode,
    mediaType: MediaType,
    message: string,
  ): void;
  /**
   * Update the media-time offset used by the host.
   */
  setMediaOffset(mediaOffset: number): void;
  /**
   * Update the current MediaSource duration.
   */
  setMediaSourceDuration(
    duration: number,
  ): HostResult<true, MediaSourceDurationUpdateErrorCode>;
  /**
   * Update the playback rate on the media element.
   */
  setPlaybackRate(playbackRate: number): void;
  /**
   * Start periodic playback observation callbacks.
   */
  startObservingPlayback(): void;
  /**
   * Notify the host that rebuffering started.
   */
  startRebuffering(): void;
  /**
   * Stop periodic playback observation callbacks.
   */
  stopObservingPlayback(): void;
  /**
   * Notify the host that rebuffering stopped.
   */
  stopRebuffering(): void;
  /**
   * Start a host-side timer and return its identifier.
   */
  timer(duration: number, reason: TimerReason): number;
  /**
   * Update content-level metadata exposed by the host.
   */
  updateContentInfo(
    minimumPosition: number | undefined,
    maximumPosition: number | undefined,
    playlistNature: PlaylistNature,
    isFinalized: boolean,
    usesProgramDateTime: boolean,
  ): void;
}

export interface WaspWasmExports {
  /**
   * Linear wasm memory used for all ABI data exchange.
   */
  readonly memory: WebAssembly.Memory;
  /**
   * Allocate raw bytes in wasm memory.
   */
  wasp_malloc(len: number): number;
  /**
   * Free raw bytes previously allocated in wasm memory.
   */
  wasp_free(ptr: number, len: number): void;
  /**
   * Update the Rust core logger level.
   */
  wasp_set_logger_level(level: number): void;
  /**
   * Construct a new dispatcher instance.
   */
  wasp_dispatcher_new(initialBandwidth: number): number;
  /**
   * Free a dispatcher instance.
   */
  wasp_dispatcher_free(ptr: number): void;
  /**
   * Start loading content into a dispatcher.
   */
  wasp_dispatcher_load_content(
    ptr: number,
    urlPtr: number,
    urlLen: number,
    hasStartingPosition: number,
    startType: StartingPositionType,
    position: number,
    initialAudioPtr: number,
    initialAudioLen: number,
  ): void;
  /**
   * Return the minimum known content position.
   */
  wasp_dispatcher_minimum_position(ptr: number): number;
  /**
   * Return the maximum known content position.
   */
  wasp_dispatcher_maximum_position(ptr: number): number;
  /**
   * Update the target playback speed for a dispatcher.
   */
  wasp_dispatcher_set_wanted_speed(ptr: number, speed: number): void;
  /**
   * Update the target buffer goal for a dispatcher.
   */
  wasp_dispatcher_set_buffer_goal(ptr: number, bufferGoal: number): void;
  /**
   * Stop a dispatcher instance.
   */
  wasp_dispatcher_stop(ptr: number): void;
  /**
   * Lock playback to a specific variant.
   */
  wasp_dispatcher_lock_variant(ptr: number, variantId: number): void;
  /**
   * Clear any variant lock on a dispatcher.
   */
  wasp_dispatcher_unlock_variant(ptr: number): void;
  /**
   * Select the audio track used by a dispatcher.
   */
  wasp_dispatcher_set_audio_track(ptr: number, trackId: number): void;
  /**
   * Set the segment request retry limit.
   */
  wasp_dispatcher_set_segment_request_max_retry(
    ptr: number,
    maxRetry: number,
  ): void;
  /**
   * Set the segment request timeout.
   */
  wasp_dispatcher_set_segment_request_timeout(
    ptr: number,
    timeout: number,
  ): void;
  /**
   * Set the segment request backoff base.
   */
  wasp_dispatcher_set_segment_backoff_base(ptr: number, base: number): void;
  /**
   * Set the segment request backoff maximum.
   */
  wasp_dispatcher_set_segment_backoff_max(ptr: number, max: number): void;
  /**
   * Set the multivariant-playlist request retry limit.
   */
  wasp_dispatcher_set_multi_variant_playlist_request_max_retry(
    ptr: number,
    maxRetry: number,
  ): void;
  /**
   * Set the multivariant-playlist request timeout.
   */
  wasp_dispatcher_set_multi_variant_playlist_request_timeout(
    ptr: number,
    timeout: number,
  ): void;
  /**
   * Set the multivariant-playlist backoff base.
   */
  wasp_dispatcher_set_multi_variant_playlist_backoff_base(
    ptr: number,
    base: number,
  ): void;
  /**
   * Set the multivariant-playlist backoff maximum.
   */
  wasp_dispatcher_set_multi_variant_playlist_backoff_max(
    ptr: number,
    max: number,
  ): void;
  /**
   * Set the media-playlist request retry limit.
   */
  wasp_dispatcher_set_media_playlist_request_max_retry(
    ptr: number,
    maxRetry: number,
  ): void;
  /**
   * Set the media-playlist request timeout.
   */
  wasp_dispatcher_set_media_playlist_request_timeout(
    ptr: number,
    timeout: number,
  ): void;
  /**
   * Set the media-playlist backoff base.
   */
  wasp_dispatcher_set_media_playlist_backoff_base(
    ptr: number,
    base: number,
  ): void;
  /**
   * Set the media-playlist backoff maximum.
   */
  wasp_dispatcher_set_media_playlist_backoff_max(
    ptr: number,
    max: number,
  ): void;
  /**
   * Forward a successful network request completion to wasm.
   */
  __web_event__request_finished(
    ptr: number,
    requestId: number,
    resourceId: number,
    resourceSize: number,
    finalUrlPtr: number,
    finalUrlLen: number,
    durationMs: number,
  ): void;
  /**
   * Forward a failed network request completion to wasm.
   */
  __web_event__request_failed(
    ptr: number,
    requestId: number,
    hasTimeouted: number,
    status: number,
  ): void;
  /**
   * Forward a MediaSource ready-state change to wasm.
   */
  __web_event__media_source_state_change(
    ptr: number,
    state: MediaSourceReadyState,
  ): void;
  /**
   * Forward a SourceBuffer buffered-range update to wasm.
   */
  __web_event__source_buffer_update(
    ptr: number,
    sourceBufferId: number,
    bufferedPtr: number,
    bufferedLen: number,
  ): void;
  /**
   * Forward a SourceBuffer creation error to wasm.
   */
  __web_event__source_buffer_creation_error(
    ptr: number,
    sourceBufferId: number,
    code: AddSourceBufferErrorCode,
    messagePtr: number,
    messageLen: number,
  ): void;
  /**
   * Forward an append-buffer failure to wasm.
   */
  __web_event__append_buffer_error(
    ptr: number,
    sourceBufferId: number,
    code: PushedSegmentErrorCode,
    bufferedPtr: number,
    bufferedLen: number,
  ): void;
  /**
   * Forward a remove-buffer failure to wasm.
   */
  __web_event__remove_buffer_error(
    ptr: number,
    sourceBufferId: number,
    bufferedPtr: number,
    bufferedLen: number,
  ): void;
  /**
   * Forward a playback observation snapshot to wasm.
   *
   * Notes:
   * - The higher-level JS wrapper for this export remains handwritten because it conditionally allocates multiple optional arrays.
   */
  __web_event__playback_tick(
    ptr: number,
    reason: PlaybackTickReason,
    currentTime: number,
    readyState: number,
    bufferedPtr: number,
    bufferedLen: number,
    paused: number,
    seeking: number,
    ended: number,
    duration: number,
    audioPtr: number,
    audioLen: number,
    videoPtr: number,
    videoLen: number,
  ): void;
  /**
   * Forward a host timer completion to wasm.
   */
  __web_event__timer_ended(ptr: number, id: number, reason: TimerReason): void;
  /**
   * Notify wasm that codec support information changed.
   */
  __web_event__codecs_support_update(ptr: number): void;
}
