#!/bin/bash

# Update gh-pages demo
# ====================
#
# This script allows to automatically update the full demo on the gh-pages
# branch.
#
# To use it:
#
#   1. Be sure that you're on a clean (no staged files and no diff) main
#      branch.
#
#   2. Call this script.
#      Some user interactions will be needed to avoid doing unwanted commits.
#
#   3. That's it!
#      A commit should have been pushed to the gh-pages.

set -e

current_branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

if ! [ "$current_branch" == "main" ]; then
  echo $current_branch
  echo "ERROR: The current branch should be main"
  exit 1;
fi

# Generate demo
npm install
npm run build:release
npm run build:demo:release
npm run doc

if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: Please commit your modifications to main"
  exit 1;
fi

tmpDemoDir=$(mktemp -d)

cp -r build/* $tmpDemoDir/ -v

# update gh-pages
git checkout gh-pages
git pull origin gh-pages
find . -maxdepth 1 ! -name '.git' -exec rm -rf {} + || true
mv $tmpDemoDir/* "."
rmdir $tmpDemoDir

if [ -n "$(git status --porcelain)" ]; then
  echo "-- Current Status on gh-pages: --"
  echo ""
  git status

  while : ; do
    echo ""
    echo "We will push the demo to gh-pages."
    REPLY=""
    read -p "do you want to continue [y/d/s/a/c/t/h] (h for help) ? " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Hh](elp)?$ ]]; then
      echo ""
      echo ""
      echo "+- help -------------------------------------------------+"
      echo "| y: commit and continue                                 |"
      echo "| d: see diff                                            |"
      echo "| s: see status                                          |"
      echo "| a: abort script from here                              |"
      echo "| c: checkout from this commit and go to the next one    |"
      echo "| t: stash this commit and go to the next one            |"
      echo "| h: see this help                                       |"
      echo "+--------------------------------------------------------+"
    elif [[ $REPLY =~ ^[Yy](es)?$ ]]; then
      git add --all
      git commit -m "demo: deploy to the gh-pages" -S
      git push origin gh-pages
      break
    elif [[ $REPLY =~ ^[Dd](iff)?$ ]]; then
      git diff || true # ignore when return 1
    elif [[ $REPLY =~ ^[Ss](tatus)?$ ]]; then
      git status
    elif [[ $REPLY =~ ^[Aa](bort)?$ ]]; then
      echo "exiting"
      exit 0
    elif [[ $REPLY =~ ^[Cc](heckout)?$ ]]; then
      git checkout .
    elif [[ $REPLY =~ ^([Tt]|([Ss]tash))?$ ]]; then
      git stash -u push
      break
    fi
  done
else
  echo "nothing to do on the gh-pages branch"
fi

git checkout main

